apiVersion: apps/v1
kind: Deployment
metadata:
  name: giftcoupon
  labels:
    app: giftcoupon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: giftcoupon
  template:
    metadata:
      labels:
        app: giftcoupon
    spec:
      containers:
        - name: giftcoupon
          image: skcc12.azurecr.io/giftcoupon:latest
          ports:
            - containerPort: 8081
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8081
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8081
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
